spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        hikari:
            maximum-pool-size: 20
            minimum-idle: 5
        password: '7^mpIf7~M=:'
        url: jdbc:mysql://49.232.173.31:3306/guns
        username: root
    jpa:
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
        show-sql: true
        hibernate:
          use-new-id-generator-mappings: false
          naming:
            physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        open-in-view: true
        properties:
          hibernate:
            enable_lazy_load_no_trans: true
    jackson:
        default-property-inclusion: NON_NULL
        #date-format: yyyy-MM-dd HH:mm:ss
        time-zone: GMT+8
        serialization:
            write-dates-as-timestamps: true
        date-format: yyyy-MM-dd HH:mm:ss
        deserialization:
          #允许对象忽略json中不存在的属性
          fail_on_unknown_properties: false
    redis:
      host: 49.232.173.31
      port: 6379
      timeout: 6000
      password: '!a-`|`#t?82'
      jedis:
        pool:
          max-active: 5120  # 连接池最大连接数（使用负值表示没有限制）
          max-wait: -1      # 连接池最大阻塞等待时间（使用负值表示没有限制）
          max-idle: 1000      # 连接池中的最大空闲连接
          min-idle: 200       # 连接池中的最小空闲连接
    main:
      allow-bean-definition-overriding: true
logging:
  config: classpath:logback.xml
server:
  port: 8080
